
package com.rapid_i.rapidhome.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-749-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RapidHomeService", targetNamespace = "http://ws.rapidhome.rapid_i.com/", wsdlLocation = "http://localhost:8080/RapidHome/RapidHomeService?wsdl")
public class RapidHomeService
    extends Service
{

    private final static URL RAPIDHOMESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.rapid_i.rapidhome.wsimport.RapidHomeService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.rapid_i.rapidhome.wsimport.RapidHomeService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/RapidHome/RapidHomeService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/RapidHome/RapidHomeService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RAPIDHOMESERVICE_WSDL_LOCATION = url;
    }

    public RapidHomeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RapidHomeService() {
        super(RAPIDHOMESERVICE_WSDL_LOCATION, new QName("http://ws.rapidhome.rapid_i.com/", "RapidHomeService"));
    }

    /**
     * 
     * @return
     *     returns RapidHome
     */
    @WebEndpoint(name = "RapidHomePort")
    public RapidHome getRapidHomePort() {
        return super.getPort(new QName("http://ws.rapidhome.rapid_i.com/", "RapidHomePort"), RapidHome.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RapidHome
     */
    @WebEndpoint(name = "RapidHomePort")
    public RapidHome getRapidHomePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.rapidhome.rapid_i.com/", "RapidHomePort"), RapidHome.class, features);
    }

}
