
package com.rapid_i.repository.wsimport.mgt;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ManagementServiceService", targetNamespace = "http://service.web.rapidanalytics.de/", wsdlLocation = "http://localhost:8080/RAWS/ManagementService?wsdl")
public class ManagementServiceService
    extends Service
{

    private final static URL MANAGEMENTSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.rapid_i.repository.wsimport.mgt.ManagementServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.rapid_i.repository.wsimport.mgt.ManagementServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/RAWS/ManagementService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/RAWS/ManagementService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MANAGEMENTSERVICESERVICE_WSDL_LOCATION = url;
    }

    public ManagementServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagementServiceService() {
        super(MANAGEMENTSERVICESERVICE_WSDL_LOCATION, new QName("http://service.web.rapidanalytics.de/", "ManagementServiceService"));
    }

    /**
     * 
     * @return
     *     returns ManagementService
     */
    @WebEndpoint(name = "ManagementServicePort")
    public ManagementService getManagementServicePort() {
        return super.getPort(new QName("http://service.web.rapidanalytics.de/", "ManagementServicePort"), ManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManagementService
     */
    @WebEndpoint(name = "ManagementServicePort")
    public ManagementService getManagementServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.web.rapidanalytics.de/", "ManagementServicePort"), ManagementService.class, features);
    }

}
