
package com.rapid_i.repository.wsimport.mgt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ManagementService", targetNamespace = "http://service.web.rapidanalytics.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManagementService {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkSetup", targetNamespace = "http://service.web.rapidanalytics.de/", className = "com.rapid_i.repository.wsimport.mgt.CheckSetup")
    @ResponseWrapper(localName = "checkSetupResponse", targetNamespace = "http://service.web.rapidanalytics.de/", className = "com.rapid_i.repository.wsimport.mgt.CheckSetupResponse")
    public boolean checkSetup();

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGlobalProperty", targetNamespace = "http://service.web.rapidanalytics.de/", className = "com.rapid_i.repository.wsimport.mgt.GetGlobalProperty")
    @ResponseWrapper(localName = "getGlobalPropertyResponse", targetNamespace = "http://service.web.rapidanalytics.de/", className = "com.rapid_i.repository.wsimport.mgt.GetGlobalPropertyResponse")
    public String getGlobalProperty(
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param value
     * @param key
     */
    @WebMethod
    @RequestWrapper(localName = "setGlobalProperty", targetNamespace = "http://service.web.rapidanalytics.de/", className = "com.rapid_i.repository.wsimport.mgt.SetGlobalProperty")
    @ResponseWrapper(localName = "setGlobalPropertyResponse", targetNamespace = "http://service.web.rapidanalytics.de/", className = "com.rapid_i.repository.wsimport.mgt.SetGlobalPropertyResponse")
    public void setGlobalProperty(
        @WebParam(name = "key", targetNamespace = "")
        String key,
        @WebParam(name = "value", targetNamespace = "")
        String value);

}
