
package com.rapidminer.deployment.client.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AccountServiceService", targetNamespace = "http://ws.update.deployment.rapid_i.com/", wsdlLocation = "http://anni:8080/UpdateServer/AccountService?wsdl")
public class AccountServiceService
    extends Service
{

    private final static URL ACCOUNTSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.rapidminer.deployment.client.wsimport.AccountServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.rapidminer.deployment.client.wsimport.AccountServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://anni:8080/UpdateServer/AccountService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://anni:8080/UpdateServer/AccountService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCOUNTSERVICESERVICE_WSDL_LOCATION = url;
    }

    public AccountServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountServiceService() {
        super(ACCOUNTSERVICESERVICE_WSDL_LOCATION, new QName("http://ws.update.deployment.rapid_i.com/", "AccountServiceService"));
    }

    /**
     * 
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountServicePort")
    public AccountService getAccountServicePort() {
        return super.getPort(new QName("http://ws.update.deployment.rapid_i.com/", "AccountServicePort"), AccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountServicePort")
    public AccountService getAccountServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.update.deployment.rapid_i.com/", "AccountServicePort"), AccountService.class, features);
    }

}
