
package com.rapid_i.repository.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProcessService_1_3", targetNamespace = "http://service.web.rapidanalytics.de/", wsdlLocation = "http://localhost:8080/RAWS/ProcessService_1_3?wsdl")
public class ProcessService13_Service
    extends Service
{

    private final static URL PROCESSSERVICE13_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.rapid_i.repository.wsimport.ProcessService13_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.rapid_i.repository.wsimport.ProcessService13_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/RAWS/ProcessService_1_3?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/RAWS/ProcessService_1_3?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROCESSSERVICE13_WSDL_LOCATION = url;
    }

    public ProcessService13_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessService13_Service() {
        super(PROCESSSERVICE13_WSDL_LOCATION, new QName("http://service.web.rapidanalytics.de/", "ProcessService_1_3"));
    }

    /**
     * 
     * @return
     *     returns ProcessService13
     */
    @WebEndpoint(name = "ProcessService_1_3Port")
    public ProcessService13 getProcessService13Port() {
        return super.getPort(new QName("http://service.web.rapidanalytics.de/", "ProcessService_1_3Port"), ProcessService13.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessService13
     */
    @WebEndpoint(name = "ProcessService_1_3Port")
    public ProcessService13 getProcessService13Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.web.rapidanalytics.de/", "ProcessService_1_3Port"), ProcessService13.class, features);
    }

}
