
package com.rapid_i.repository.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProcessService", targetNamespace = "http://service.web.rapidanalytics.de/", wsdlLocation = "http://localhost:8080/RAWS/ProcessService?wsdl")
public class ProcessService_Service
    extends Service
{

    private final static URL PROCESSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.rapid_i.repository.wsimport.ProcessService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.rapid_i.repository.wsimport.ProcessService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/RAWS/ProcessService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/RAWS/ProcessService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROCESSSERVICE_WSDL_LOCATION = url;
    }

    public ProcessService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessService_Service() {
        super(PROCESSSERVICE_WSDL_LOCATION, new QName("http://service.web.rapidanalytics.de/", "ProcessService"));
    }

    /**
     * 
     * @return
     *     returns ProcessService
     */
    @WebEndpoint(name = "ProcessServicePort")
    public ProcessService getProcessServicePort() {
        return super.getPort(new QName("http://service.web.rapidanalytics.de/", "ProcessServicePort"), ProcessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessService
     */
    @WebEndpoint(name = "ProcessServicePort")
    public ProcessService getProcessServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.web.rapidanalytics.de/", "ProcessServicePort"), ProcessService.class, features);
    }

}
