
package com.rapid_i.repository.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RAInfoService", targetNamespace = "http://service.web.rapidanalytics.de/", wsdlLocation = "http://localhost:8080/RAWS/RAInfoService?wsdl")
public class RAInfoService_Service
    extends Service
{

    private final static URL RAINFOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.rapid_i.repository.wsimport.RAInfoService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.rapid_i.repository.wsimport.RAInfoService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/RAWS/RAInfoService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/RAWS/RAInfoService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RAINFOSERVICE_WSDL_LOCATION = url;
    }

    public RAInfoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RAInfoService_Service() {
        super(RAINFOSERVICE_WSDL_LOCATION, new QName("http://service.web.rapidanalytics.de/", "RAInfoService"));
    }

    /**
     * 
     * @return
     *     returns RAInfoService
     */
    @WebEndpoint(name = "RAInfoServicePort")
    public RAInfoService getRAInfoServicePort() {
        return super.getPort(new QName("http://service.web.rapidanalytics.de/", "RAInfoServicePort"), RAInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RAInfoService
     */
    @WebEndpoint(name = "RAInfoServicePort")
    public RAInfoService getRAInfoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.web.rapidanalytics.de/", "RAInfoServicePort"), RAInfoService.class, features);
    }

}
