
package com.rapid_i.repository.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RepositoryService", targetNamespace = "http://service.web.rapidanalytics.de/", wsdlLocation = "http://localhost:8080/RAWS/RepositoryService?wsdl")
public class RepositoryService_Service
    extends Service
{

    private final static URL REPOSITORYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.rapid_i.repository.wsimport.RepositoryService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.rapid_i.repository.wsimport.RepositoryService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/RAWS/RepositoryService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/RAWS/RepositoryService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REPOSITORYSERVICE_WSDL_LOCATION = url;
    }

    public RepositoryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RepositoryService_Service() {
        super(REPOSITORYSERVICE_WSDL_LOCATION, new QName("http://service.web.rapidanalytics.de/", "RepositoryService"));
    }

    /**
     * 
     * @return
     *     returns RepositoryService
     */
    @WebEndpoint(name = "RepositoryServicePort")
    public RepositoryService getRepositoryServicePort() {
        return super.getPort(new QName("http://service.web.rapidanalytics.de/", "RepositoryServicePort"), RepositoryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RepositoryService
     */
    @WebEndpoint(name = "RepositoryServicePort")
    public RepositoryService getRepositoryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.web.rapidanalytics.de/", "RepositoryServicePort"), RepositoryService.class, features);
    }

}
